eureka:
  client:
    service-url:
      defaultZone: https://service-registry-leeg.onrender.com/eureka
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    hostname: student-service-fowj.onrender.com