services:
  mongodb:
    container_name: ms_mongodb
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: ms_mongodb
      MONGO_INITDB_ROOT_PASSWORD: ms_mongo_db
    networks:
      - microservices-net
    restart: unless-stopped

  mongo-express:
    container_name: ms_mongo_express
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ms_mongodb
      ME_CONFIG_MONGODB_ADMINPASSWORD: ms_mongo_db
      ME_CONFIG_MONGODB_SERVER: ms_mongodb
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  mongo:
