server:
  port: 8765

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "https://*.vercel.app"
              - "http://localhost:*"
            allowedOrigins:
              - "https://colab-bridge-git-main-hetbhagatji09-gmailcoms-projects.vercel.app"
              - "https://colab-bridge-hcz38o2w5-hetbhagatji09-gmailcoms-projects.vercel.app"
              - "http://localhost:3000"
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - HEAD
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
            exposedHeaders:
              - "Authorization"
              - "Content-Type"
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      routes:
        - id: authentication-service
          uri: https://authentication-service-vfxn.onrender.com
          predicates:
            - Path=/auth/**

        - id: admin-service
          uri: https://admin-service-2nj1.onrender.com
          predicates:
            - Path=/ADMIN-SERVICE/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter

        - id: faculty-service
          uri: https://faculty-service.onrender.com
          predicates:
            - Path=/FACULTY-SERVICE/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter

        - id: student-service
          uri: https://student-service-fowj.onrender.com
          predicates:
            - Path=/STUDENT-SERVICE/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
























#    register-with-eureka: true
#    fetch-registry: true
#  instance:
#    prefer-ip-address: true
#,https://delightful-victory-production.up.railway.app/eureka/,http://localhost:8761/eureka/
#server:
#  port: 8765
#
#spring:
#  application:
#    name: API-GATEWAY
#
#  cloud:
#    gateway:
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
#
#      routes:
#        - id: authentication-service
#          uri: https://delightful-victory-production.up.railway.app
#          predicates:
#            - Path=/auth/**
#            - Path=/AUTHENTICATION-SERVICE/**
#
#        - id: admin-service
#          uri: lb://ADMIN-SERVICE
#          predicates:
#            - Path=/admin/**
#            - Path=/ADMIN-SERVICE/**
#
#        - id: faculty-service
#          uri: https://faculty-service-production.up.railway.app
#          predicates:
#            - Path=/faculty/**
#            - Path=/FACULTY-SERVICE/**
#
#        - id: student-service
#          uri: lb://STUDENT-SERVICE
#          predicates:
#            - Path=/student/**
#            - Path=/STUDENT-SERVICE/**
#
#eureka:
#  client:
#    service-url:
#      defaultZone: https://localhost:8761/eureka
#    register-with-eureka: true
#    fetch-registry: true
#  instance:
#    prefer-ip-address: true
##https://service-registry-production-97f5.up.railway.app/eureka