server:
  port: 8765

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/auth/**


        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin/**

        - id: faculty-service
          uri: lb://FACULTY-SERVICE
          predicates:
            - Path=/faculty/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter


        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/student/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


#  http://localhost:8765/faculty/api/faculty/studentproject/31/count