server:
  port: 8765

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

      routes:
        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/auth/**,/AUTHENTICATION-SERVICE/**

        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin/**,/ADMIN-SERVICE/**

        - id: faculty-service
          uri: lb://FACULTY-SERVICE
          predicates:
            - Path=/faculty/**,/FACULTY-SERVICE/**

        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/student/**,/STUDENT-SERVICE/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#server:
#  port: 8765
#
#spring:
#  application:
#    name: API-GATEWAY
#
#  cloud:
#    gateway:
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
#
#      routes:
#        - id: authentication-service
#          uri: lb://AUTHENTICATION-SERVICE
#          predicates:
#            - Path=/auth/**,/AUTHENTICATION-SERVICE/**
#
#        - id: admin-service
#          uri: lb://ADMIN-SERVICE
#          predicates:
#            - Path=/admin/**,/ADMIN-SERVICE/**
#
#        - id: faculty-service
#          uri: lb://FACULTY-SERVICE
#          predicates:
#            - Path=/faculty/**,/FACULTY-SERVICE/**
#
#        - id: student-service
#          uri: lb://STUDENT-SERVICE
#          predicates:
#            - Path=/student/**,/STUDENT-SERVICE/**
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka